# Site settings
title: Hacker Hours UMN
email: whit0694@umn.edu
description: "Hacker Hours UMN"
baseurl: ""
url: "http://hackerhours.github.umn.edu"

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
excerpt_separator: <!--break-->
exclude: ["bin","README.md", "bundle", "Gemfile", "Gemfile.lock"]

kramdown:
  input: GFM
  syntax_highlighter: pygments
